services:
  - type: web
    name: voltrex
    runtime: python
    plan: free
    region: oregon
    branch: main
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    autoDeploy: true
